site_name: Protobuff Exemplar
site_url: https://pradyothadavi.github.io/protobuffer-exemplar/
repo_url: https://github.com/pradyothadavi/protobuffer-exemplar
site_author: Pradyot H Adavi

theme:
  name: material

nav:
  - 'Introduction': index.md
  - 'Setup': protocsetup.md
  - 'Examples': examples.md
