// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: name.proto

package model.proto;

public final class NameOuterClass {
  private NameOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Name_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Name_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nname.proto\"B\n\004Name\022\022\n\nfirst_name\030\001 \001(\t" +
      "\022\023\n\013middle_name\030\002 \001(\t\022\021\n\tlast_name\030\003 \001(\t" +
      "B\017\n\013model.protoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Name_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Name_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Name_descriptor,
        new java.lang.String[] { "FirstName", "MiddleName", "LastName", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
