// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: name.proto

package model.proto;

public interface NameOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Name)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string first_name = 1;</code>
   */
  java.lang.String getFirstName();
  /**
   * <code>string first_name = 1;</code>
   */
  com.google.protobuf.ByteString
      getFirstNameBytes();

  /**
   * <code>string middle_name = 2;</code>
   */
  java.lang.String getMiddleName();
  /**
   * <code>string middle_name = 2;</code>
   */
  com.google.protobuf.ByteString
      getMiddleNameBytes();

  /**
   * <code>string last_name = 3;</code>
   */
  java.lang.String getLastName();
  /**
   * <code>string last_name = 3;</code>
   */
  com.google.protobuf.ByteString
      getLastNameBytes();
}
