// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: person.proto

package model.proto;

public interface PersonOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Person)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.Name name = 16;</code>
   */
  boolean hasName();
  /**
   * <code>.Name name = 16;</code>
   */
  model.proto.Name getName();
  /**
   * <code>.Name name = 16;</code>
   */
  model.proto.NameOrBuilder getNameOrBuilder();

  /**
   * <code>uint64 age = 17;</code>
   */
  long getAge();
}
