// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Test3.proto

package model.proto;

public final class Test3OuterClass {
  private Test3OuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Test3_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Test3_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013Test3.proto\032\013Test1.proto\"\032\n\005Test3\022\021\n\001c" +
      "\030\003 \001(\0132\006.Test1B\017\n\013model.protoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          model.proto.Test1OuterClass.getDescriptor(),
        });
    internal_static_Test3_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Test3_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Test3_descriptor,
        new java.lang.String[] { "C", });
    model.proto.Test1OuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
