// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Test5.proto

package model.proto;

public interface Test5OrBuilder extends
    // @@protoc_insertion_point(interface_extends:Test5)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>fixed64 e = 5;</code>
   */
  long getE();
}
