// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Test2.proto

package model.proto;

public interface Test2OrBuilder extends
    // @@protoc_insertion_point(interface_extends:Test2)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string b = 2;</code>
   */
  java.lang.String getB();
  /**
   * <code>string b = 2;</code>
   */
  com.google.protobuf.ByteString
      getBBytes();
}
