// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Test4.proto

package model.proto;

public interface Test4OrBuilder extends
    // @@protoc_insertion_point(interface_extends:Test4)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>fixed32 d = 4;</code>
   */
  int getD();
}
