// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Test1.proto

package model.proto;

public interface Test1OrBuilder extends
    // @@protoc_insertion_point(interface_extends:Test1)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 a = 1;</code>
   */
  int getA();
}
