// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Test3.proto

package model.proto;

/**
 * Protobuf type {@code Test3}
 */
public  final class Test3 extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Test3)
    Test3OrBuilder {
private static final long serialVersionUID = 0L;
  // Use Test3.newBuilder() to construct.
  private Test3(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Test3() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Test3();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Test3(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 26: {
            model.proto.Test1.Builder subBuilder = null;
            if (c_ != null) {
              subBuilder = c_.toBuilder();
            }
            c_ = input.readMessage(model.proto.Test1.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(c_);
              c_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return model.proto.Test3OuterClass.internal_static_Test3_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return model.proto.Test3OuterClass.internal_static_Test3_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            model.proto.Test3.class, model.proto.Test3.Builder.class);
  }

  public static final int C_FIELD_NUMBER = 3;
  private model.proto.Test1 c_;
  /**
   * <code>.Test1 c = 3;</code>
   */
  public boolean hasC() {
    return c_ != null;
  }
  /**
   * <code>.Test1 c = 3;</code>
   */
  public model.proto.Test1 getC() {
    return c_ == null ? model.proto.Test1.getDefaultInstance() : c_;
  }
  /**
   * <code>.Test1 c = 3;</code>
   */
  public model.proto.Test1OrBuilder getCOrBuilder() {
    return getC();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (c_ != null) {
      output.writeMessage(3, getC());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (c_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getC());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof model.proto.Test3)) {
      return super.equals(obj);
    }
    model.proto.Test3 other = (model.proto.Test3) obj;

    if (hasC() != other.hasC()) return false;
    if (hasC()) {
      if (!getC()
          .equals(other.getC())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasC()) {
      hash = (37 * hash) + C_FIELD_NUMBER;
      hash = (53 * hash) + getC().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static model.proto.Test3 parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static model.proto.Test3 parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static model.proto.Test3 parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static model.proto.Test3 parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static model.proto.Test3 parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static model.proto.Test3 parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static model.proto.Test3 parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static model.proto.Test3 parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static model.proto.Test3 parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static model.proto.Test3 parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static model.proto.Test3 parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static model.proto.Test3 parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(model.proto.Test3 prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Test3}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Test3)
      model.proto.Test3OrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return model.proto.Test3OuterClass.internal_static_Test3_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return model.proto.Test3OuterClass.internal_static_Test3_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              model.proto.Test3.class, model.proto.Test3.Builder.class);
    }

    // Construct using model.proto.Test3.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (cBuilder_ == null) {
        c_ = null;
      } else {
        c_ = null;
        cBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return model.proto.Test3OuterClass.internal_static_Test3_descriptor;
    }

    @java.lang.Override
    public model.proto.Test3 getDefaultInstanceForType() {
      return model.proto.Test3.getDefaultInstance();
    }

    @java.lang.Override
    public model.proto.Test3 build() {
      model.proto.Test3 result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public model.proto.Test3 buildPartial() {
      model.proto.Test3 result = new model.proto.Test3(this);
      if (cBuilder_ == null) {
        result.c_ = c_;
      } else {
        result.c_ = cBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof model.proto.Test3) {
        return mergeFrom((model.proto.Test3)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(model.proto.Test3 other) {
      if (other == model.proto.Test3.getDefaultInstance()) return this;
      if (other.hasC()) {
        mergeC(other.getC());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      model.proto.Test3 parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (model.proto.Test3) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private model.proto.Test1 c_;
    private com.google.protobuf.SingleFieldBuilderV3<
        model.proto.Test1, model.proto.Test1.Builder, model.proto.Test1OrBuilder> cBuilder_;
    /**
     * <code>.Test1 c = 3;</code>
     */
    public boolean hasC() {
      return cBuilder_ != null || c_ != null;
    }
    /**
     * <code>.Test1 c = 3;</code>
     */
    public model.proto.Test1 getC() {
      if (cBuilder_ == null) {
        return c_ == null ? model.proto.Test1.getDefaultInstance() : c_;
      } else {
        return cBuilder_.getMessage();
      }
    }
    /**
     * <code>.Test1 c = 3;</code>
     */
    public Builder setC(model.proto.Test1 value) {
      if (cBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        c_ = value;
        onChanged();
      } else {
        cBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.Test1 c = 3;</code>
     */
    public Builder setC(
        model.proto.Test1.Builder builderForValue) {
      if (cBuilder_ == null) {
        c_ = builderForValue.build();
        onChanged();
      } else {
        cBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.Test1 c = 3;</code>
     */
    public Builder mergeC(model.proto.Test1 value) {
      if (cBuilder_ == null) {
        if (c_ != null) {
          c_ =
            model.proto.Test1.newBuilder(c_).mergeFrom(value).buildPartial();
        } else {
          c_ = value;
        }
        onChanged();
      } else {
        cBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.Test1 c = 3;</code>
     */
    public Builder clearC() {
      if (cBuilder_ == null) {
        c_ = null;
        onChanged();
      } else {
        c_ = null;
        cBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.Test1 c = 3;</code>
     */
    public model.proto.Test1.Builder getCBuilder() {
      
      onChanged();
      return getCFieldBuilder().getBuilder();
    }
    /**
     * <code>.Test1 c = 3;</code>
     */
    public model.proto.Test1OrBuilder getCOrBuilder() {
      if (cBuilder_ != null) {
        return cBuilder_.getMessageOrBuilder();
      } else {
        return c_ == null ?
            model.proto.Test1.getDefaultInstance() : c_;
      }
    }
    /**
     * <code>.Test1 c = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        model.proto.Test1, model.proto.Test1.Builder, model.proto.Test1OrBuilder> 
        getCFieldBuilder() {
      if (cBuilder_ == null) {
        cBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            model.proto.Test1, model.proto.Test1.Builder, model.proto.Test1OrBuilder>(
                getC(),
                getParentForChildren(),
                isClean());
        c_ = null;
      }
      return cBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Test3)
  }

  // @@protoc_insertion_point(class_scope:Test3)
  private static final model.proto.Test3 DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new model.proto.Test3();
  }

  public static model.proto.Test3 getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Test3>
      PARSER = new com.google.protobuf.AbstractParser<Test3>() {
    @java.lang.Override
    public Test3 parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Test3(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Test3> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Test3> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public model.proto.Test3 getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

