// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Test3.proto

package model.proto;

public interface Test3OrBuilder extends
    // @@protoc_insertion_point(interface_extends:Test3)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.Test1 c = 3;</code>
   */
  boolean hasC();
  /**
   * <code>.Test1 c = 3;</code>
   */
  model.proto.Test1 getC();
  /**
   * <code>.Test1 c = 3;</code>
   */
  model.proto.Test1OrBuilder getCOrBuilder();
}
